apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wid-pvc-mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: do-block-storage