apiVersion: v1
kind: Service
metadata:
  name: api-emb
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: api-emb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-emb
spec:
  selector:
    matchLabels:
      app: api-emb
  replicas: 2
  template:
    metadata:
      labels:
        app: api-emb
    spec:
      containers:
      - name: api-emb
        image: wanderindev/api-emb:latest
        ports:
        - containerPort: 80
