apiVersion: v1
kind: Service
metadata:
  name: adg-web
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: adg-web
---
apiVersion: v1
kind: Service
metadata:
  name: adg-feedback
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: adg-feedback
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adg-web
spec:
  selector:
    matchLabels:
      app: adg-web
  replicas: 1
  template:
    metadata:
      labels:
        app: adg-web
    spec:
      containers:
      - name: adg-web
        image: wanderindev/adg-web:latest
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/instance-type: "s-1vcpu-2gb"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adg-feedback
spec:
  selector:
    matchLabels:
      app: adg-feedback
  replicas: 1
  template:
    metadata:
      labels:
        app: adg-feedback
    spec:
      containers:
      - name: adg-feedback
        image: wanderindev/adg-feedback:latest
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/instance-type: "s-1vcpu-2gb"