apiVersion: v1
kind: Service
metadata:
  name: atelier-web
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: atelier-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atelier-web
spec:
  selector:
    matchLabels:
      app: atelier-web
  replicas: 2
  template:
    metadata:
      labels:
        app: atelier-web
    spec:
      containers:
      - name: atelier-web
        image: wanderindev/atelier-web:latest
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/instance-type: "s-1vcpu-2gb"