apiVersion: v1
kind: Service
metadata:
  name: feliuio-web
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: feliuio-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feliuio-web
spec:
  selector:
    matchLabels:
      app: feliuio-web
  replicas: 1
  template:
    metadata:
      labels:
        app: feliuio-web
    spec:
      containers:
      - name: feliuio-web
        image: wanderindev/feliuio-web:latest
        ports:
        - containerPort: 80
