apiVersion: v1
kind: Service
metadata:
  name: hr-rest
spec:
  ports:
  - port: 80
    targetPort: 5002
  selector:
    app: hr-rest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-rest
spec:
  selector:
    matchLabels:
      app: hr-rest
  replicas: 2
  template:
    metadata:
      labels:
        app: hr-rest
    spec:
      containers:
      - name: hr-rest
        image: wanderindev/hr-rest:latest
        ports:
        - containerPort: 5002
      nodeSelector:
        beta.kubernetes.io/instance-type: "s-1vcpu-2gb"