apiVersion: v1
kind: Service
metadata:
  name: usl-web
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: usl-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usl-web
spec:
  selector:
    matchLabels:
      app: usl-web
  replicas: 1
  template:
    metadata:
      labels:
        app: usl-web
    spec:
      containers:
      - name: usl-web
        image: wanderindev/usl-web:latest
        ports:
        - containerPort: 80
      nodeSelector:
        type: "worker"