apiVersion: v1
kind: Service
metadata:
  name: wallcouture-web
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: wallcouture-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallcouture-web
spec:
  selector:
    matchLabels:
      app: wallcouture-web
  replicas: 1
  template:
    metadata:
      labels:
        app: wallcouture-web
    spec:
      containers:
      - name: wallcouture-web
        image: wanderindev/wallcouture-web:latest
        ports:
        - containerPort: 80
      nodeSelector:
        type: "worker"